// <auto-generated/>
#pragma warning disable CS0618
using KrogerMcp.Generated.Products.Kiota.Models.APIError.Products;
using KrogerMcp.Generated.Products.Kiota.Models.APIError;
using KrogerMcp.Generated.Products.Kiota.Models.Products;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace KrogerMcp.Generated.Products.Kiota.V1.Products.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\products\{id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ProductsItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::KrogerMcp.Generated.Products.Kiota.V1.Products.Item.ProductsItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProductsItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/products/{id}{?filter%2ElocationId*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::KrogerMcp.Generated.Products.Kiota.V1.Products.Item.ProductsItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProductsItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/products/{id}{?filter%2ElocationId*}", rawUrl)
        {
        }
        /// <summary>
        /// Provides access to the details of a specific product by using the 13 digit `productId`. If converting from a barcode omit the check digit.  To return the product price, availability, and aisle location, you must include the `filter.locationId` query parameter.
        /// </summary>
        /// <returns>A <see cref="global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductPayloadModel"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::KrogerMcp.Generated.Products.Kiota.Models.APIError.Unauthorized">When receiving a 401 status code</exception>
        /// <exception cref="global::KrogerMcp.Generated.Products.Kiota.Models.APIError.Forbidden">When receiving a 403 status code</exception>
        /// <exception cref="global::KrogerMcp.Generated.Products.Kiota.Models.APIError.Products.ServerError">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductPayloadModel?> GetAsync(Action<RequestConfiguration<global::KrogerMcp.Generated.Products.Kiota.V1.Products.Item.ProductsItemRequestBuilder.ProductsItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductPayloadModel> GetAsync(Action<RequestConfiguration<global::KrogerMcp.Generated.Products.Kiota.V1.Products.Item.ProductsItemRequestBuilder.ProductsItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::KrogerMcp.Generated.Products.Kiota.Models.APIError.Unauthorized.CreateFromDiscriminatorValue },
                { "403", global::KrogerMcp.Generated.Products.Kiota.Models.APIError.Forbidden.CreateFromDiscriminatorValue },
                { "500", global::KrogerMcp.Generated.Products.Kiota.Models.APIError.Products.ServerError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductPayloadModel>(requestInfo, global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductPayloadModel.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Provides access to the details of a specific product by using the 13 digit `productId`. If converting from a barcode omit the check digit.  To return the product price, availability, and aisle location, you must include the `filter.locationId` query parameter.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::KrogerMcp.Generated.Products.Kiota.V1.Products.Item.ProductsItemRequestBuilder.ProductsItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::KrogerMcp.Generated.Products.Kiota.V1.Products.Item.ProductsItemRequestBuilder.ProductsItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::KrogerMcp.Generated.Products.Kiota.V1.Products.Item.ProductsItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::KrogerMcp.Generated.Products.Kiota.V1.Products.Item.ProductsItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::KrogerMcp.Generated.Products.Kiota.V1.Products.Item.ProductsItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Provides access to the details of a specific product by using the 13 digit `productId`. If converting from a barcode omit the check digit.  To return the product price, availability, and aisle location, you must include the `filter.locationId` query parameter.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ProductsItemRequestBuilderGetQueryParameters 
        {
            /// <summary>The locationId of the location. When using this filter, only products available at that location are returned.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter%2ElocationId")]
            public string? FilterLocationId { get; set; }
#nullable restore
#else
            [QueryParameter("filter%2ElocationId")]
            public string FilterLocationId { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ProductsItemRequestBuilderGetRequestConfiguration : RequestConfiguration<global::KrogerMcp.Generated.Products.Kiota.V1.Products.Item.ProductsItemRequestBuilder.ProductsItemRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
