// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace KrogerMcp.Generated.Products.Kiota.V1.Products
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetFilterFulfillmentQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "ais")]
        #pragma warning disable CS1591
        Ais,
        #pragma warning restore CS1591
        [EnumMember(Value = "csp")]
        #pragma warning disable CS1591
        Csp,
        #pragma warning restore CS1591
        [EnumMember(Value = "dth")]
        #pragma warning disable CS1591
        Dth,
        #pragma warning restore CS1591
        [EnumMember(Value = "sth")]
        #pragma warning disable CS1591
        Sth,
        #pragma warning restore CS1591
    }
}
