// <auto-generated/>
#pragma warning disable CS0618
using KrogerMcp.Generated.Products.Kiota.Models.APIError.Products;
using KrogerMcp.Generated.Products.Kiota.Models.APIError;
using KrogerMcp.Generated.Products.Kiota.Models.Products;
using KrogerMcp.Generated.Products.Kiota.V1.Products.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace KrogerMcp.Generated.Products.Kiota.V1.Products
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\products
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ProductsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the KrogerMcp.Generated.Products.Kiota.v1.products.item collection</summary>
        /// <param name="position">The id of the product</param>
        /// <returns>A <see cref="global::KrogerMcp.Generated.Products.Kiota.V1.Products.Item.ProductsItemRequestBuilder"/></returns>
        public global::KrogerMcp.Generated.Products.Kiota.V1.Products.Item.ProductsItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::KrogerMcp.Generated.Products.Kiota.V1.Products.Item.ProductsItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::KrogerMcp.Generated.Products.Kiota.V1.Products.ProductsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProductsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/products{?filter%2Ebrand*,filter%2Efulfillment*,filter%2Elimit*,filter%2ElocationId*,filter%2EproductId*,filter%2Estart*,filter%2Eterm*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::KrogerMcp.Generated.Products.Kiota.V1.Products.ProductsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ProductsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/products{?filter%2Ebrand*,filter%2Efulfillment*,filter%2Elimit*,filter%2ElocationId*,filter%2EproductId*,filter%2Estart*,filter%2Eterm*}", rawUrl)
        {
        }
        /// <summary>
        /// Allows you to find products by passing in either a search term or product Id.### Initial Search Value RequiredAn initial search value is requred for all requests. You can use either of the following parameters as an initial search value: `filter.term` - When using the term parameter, the API performs a fuzzy search based on the term provided in the string. Search results are based on how relevant the term is to the product description.`filter.brand` - When using the brand parameter, the API performs a search based on the brand provided in the string. Search results only contain products that match the brand queried for.`filter.productId` - When using the productId parameter, the API performs a query to find an exact match. The format for the productId is a 13 digit number.  NOTE: If converting from a barcode omit the check digit.
        /// </summary>
        /// <returns>A <see cref="global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductsPayloadModel"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::KrogerMcp.Generated.Products.Kiota.Models.APIError.Unauthorized">When receiving a 401 status code</exception>
        /// <exception cref="global::KrogerMcp.Generated.Products.Kiota.Models.APIError.Forbidden">When receiving a 403 status code</exception>
        /// <exception cref="global::KrogerMcp.Generated.Products.Kiota.Models.APIError.Products.ServerError">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductsPayloadModel?> GetAsync(Action<RequestConfiguration<global::KrogerMcp.Generated.Products.Kiota.V1.Products.ProductsRequestBuilder.ProductsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductsPayloadModel> GetAsync(Action<RequestConfiguration<global::KrogerMcp.Generated.Products.Kiota.V1.Products.ProductsRequestBuilder.ProductsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::KrogerMcp.Generated.Products.Kiota.Models.APIError.Unauthorized.CreateFromDiscriminatorValue },
                { "403", global::KrogerMcp.Generated.Products.Kiota.Models.APIError.Forbidden.CreateFromDiscriminatorValue },
                { "500", global::KrogerMcp.Generated.Products.Kiota.Models.APIError.Products.ServerError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductsPayloadModel>(requestInfo, global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductsPayloadModel.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Allows you to find products by passing in either a search term or product Id.### Initial Search Value RequiredAn initial search value is requred for all requests. You can use either of the following parameters as an initial search value: `filter.term` - When using the term parameter, the API performs a fuzzy search based on the term provided in the string. Search results are based on how relevant the term is to the product description.`filter.brand` - When using the brand parameter, the API performs a search based on the brand provided in the string. Search results only contain products that match the brand queried for.`filter.productId` - When using the productId parameter, the API performs a query to find an exact match. The format for the productId is a 13 digit number.  NOTE: If converting from a barcode omit the check digit.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::KrogerMcp.Generated.Products.Kiota.V1.Products.ProductsRequestBuilder.ProductsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::KrogerMcp.Generated.Products.Kiota.V1.Products.ProductsRequestBuilder.ProductsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::KrogerMcp.Generated.Products.Kiota.V1.Products.ProductsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::KrogerMcp.Generated.Products.Kiota.V1.Products.ProductsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::KrogerMcp.Generated.Products.Kiota.V1.Products.ProductsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Allows you to find products by passing in either a search term or product Id.### Initial Search Value RequiredAn initial search value is requred for all requests. You can use either of the following parameters as an initial search value: `filter.term` - When using the term parameter, the API performs a fuzzy search based on the term provided in the string. Search results are based on how relevant the term is to the product description.`filter.brand` - When using the brand parameter, the API performs a search based on the brand provided in the string. Search results only contain products that match the brand queried for.`filter.productId` - When using the productId parameter, the API performs a query to find an exact match. The format for the productId is a 13 digit number.  NOTE: If converting from a barcode omit the check digit.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ProductsRequestBuilderGetQueryParameters 
        {
            /// <summary>The brand name of the products to return. When using this filter, only products by that brand are returned. Brand names are case-sensitive, and lists must be pipe-separated.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter%2Ebrand")]
            public string? FilterBrand { get; set; }
#nullable restore
#else
            [QueryParameter("filter%2Ebrand")]
            public string FilterBrand { get; set; }
#endif
            /// <summary>&apos;The available fulfillment types of the product(s) to return.Fulfillment types are case-sensitive, and lists must be comma-separated.Must be one or more of the follow types: &lt;ul&gt; &lt;li&gt; `ais` - Available InStore&lt;/li&gt; &lt;li&gt; `csp` - Curbside Pickup&lt;/li&gt; &lt;li&gt; `dth` - Delivery To Home&lt;/li&gt;&lt;li&gt; `sth` - Ship To Home&lt;/li&gt; &lt;/ui&gt;&apos;</summary>
            [Obsolete("This property is deprecated, use FilterFulfillmentAsGetFilterFulfillmentQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter%2Efulfillment")]
            public string? FilterFulfillment { get; set; }
#nullable restore
#else
            [QueryParameter("filter%2Efulfillment")]
            public string FilterFulfillment { get; set; }
#endif
            /// <summary>&apos;The available fulfillment types of the product(s) to return.Fulfillment types are case-sensitive, and lists must be comma-separated.Must be one or more of the follow types: &lt;ul&gt; &lt;li&gt; `ais` - Available InStore&lt;/li&gt; &lt;li&gt; `csp` - Curbside Pickup&lt;/li&gt; &lt;li&gt; `dth` - Delivery To Home&lt;/li&gt;&lt;li&gt; `sth` - Ship To Home&lt;/li&gt; &lt;/ui&gt;&apos;</summary>
            [QueryParameter("filter%2Efulfillment")]
            public global::KrogerMcp.Generated.Products.Kiota.V1.Products.GetFilterFulfillmentQueryParameterType? FilterFulfillmentAsGetFilterFulfillmentQueryParameterType { get; set; }
            /// <summary>The number of products to return.</summary>
            [QueryParameter("filter%2Elimit")]
            public int? FilterLimit { get; set; }
            /// <summary>The locationId of the location. When using this filter, only products available at that location are returned.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter%2ElocationId")]
            public string? FilterLocationId { get; set; }
#nullable restore
#else
            [QueryParameter("filter%2ElocationId")]
            public string FilterLocationId { get; set; }
#endif
            /// <summary>The productId of the products(s) to return. For more than one item, the list must be comma-separated. When used, all other query parameters are ignored.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter%2EproductId")]
            public string? FilterProductId { get; set; }
#nullable restore
#else
            [QueryParameter("filter%2EproductId")]
            public string FilterProductId { get; set; }
#endif
            /// <summary>The number of products to skip.</summary>
            [QueryParameter("filter%2Estart")]
            public int? FilterStart { get; set; }
            /// <summary>A search term to filter product results. As an example, you could input _milk_, _bread_, or _salt_. &lt;br&gt;&lt;br&gt;&lt;b&gt;Note&lt;/b&gt; - Search terms are limited to a maximum of 8 words. Each new space in the search term denotes a new word.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter%2Eterm")]
            public string? FilterTerm { get; set; }
#nullable restore
#else
            [QueryParameter("filter%2Eterm")]
            public string FilterTerm { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ProductsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::KrogerMcp.Generated.Products.Kiota.V1.Products.ProductsRequestBuilder.ProductsRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
