// <auto-generated/>
#pragma warning disable CS0618
using KrogerMcp.Generated.Locations.Kiota.Models.APIError.Locations;
using KrogerMcp.Generated.Locations.Kiota.Models.APIError;
using KrogerMcp.Generated.Locations.Kiota.Models.Locations;
using KrogerMcp.Generated.Locations.Kiota.V1.Departments.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace KrogerMcp.Generated.Locations.Kiota.V1.Departments
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\departments
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DepartmentsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the KrogerMcp.Generated.Locations.Kiota.v1.departments.item collection</summary>
        /// <param name="position">The departmentId of the department to return.</param>
        /// <returns>A <see cref="global::KrogerMcp.Generated.Locations.Kiota.V1.Departments.Item.DepartmentsItemRequestBuilder"/></returns>
        public global::KrogerMcp.Generated.Locations.Kiota.V1.Departments.Item.DepartmentsItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::KrogerMcp.Generated.Locations.Kiota.V1.Departments.Item.DepartmentsItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::KrogerMcp.Generated.Locations.Kiota.V1.Departments.DepartmentsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DepartmentsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/departments", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::KrogerMcp.Generated.Locations.Kiota.V1.Departments.DepartmentsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DepartmentsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/departments", rawUrl)
        {
        }
        /// <summary>
        /// Provides access to a list of all departments, including departments of chains owned by The Kroger Co.
        /// </summary>
        /// <returns>A <see cref="global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.DepartmentsResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::KrogerMcp.Generated.Locations.Kiota.Models.APIError.APIError">When receiving a 400 status code</exception>
        /// <exception cref="global::KrogerMcp.Generated.Locations.Kiota.Models.APIError.Unauthorized">When receiving a 401 status code</exception>
        /// <exception cref="global::KrogerMcp.Generated.Locations.Kiota.Models.APIError.Locations.ServerError">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.DepartmentsResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.DepartmentsResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::KrogerMcp.Generated.Locations.Kiota.Models.APIError.APIError.CreateFromDiscriminatorValue },
                { "401", global::KrogerMcp.Generated.Locations.Kiota.Models.APIError.Unauthorized.CreateFromDiscriminatorValue },
                { "500", global::KrogerMcp.Generated.Locations.Kiota.Models.APIError.Locations.ServerError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.DepartmentsResponse>(requestInfo, global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.DepartmentsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Provides access to a list of all departments, including departments of chains owned by The Kroger Co.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::KrogerMcp.Generated.Locations.Kiota.V1.Departments.DepartmentsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::KrogerMcp.Generated.Locations.Kiota.V1.Departments.DepartmentsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::KrogerMcp.Generated.Locations.Kiota.V1.Departments.DepartmentsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DepartmentsRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
