// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace KrogerMcp.Generated.Cart.Kiota.Models.Cart
{
    /// <summary>An optional value representing a modality including: DELIVERY, PICKUP.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CartItemModel_modality
    {
        [EnumMember(Value = "DELIVERY")]
        #pragma warning disable CS1591
        DELIVERY,
        #pragma warning restore CS1591
        [EnumMember(Value = "PICKUP")]
        #pragma warning disable CS1591
        PICKUP,
        #pragma warning restore CS1591
    }
}
