// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace KrogerMcp.Generated.Cart.Kiota.Models.Cart
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CartItemModel : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>An optional value representing a modality including: DELIVERY, PICKUP.</summary>
        public global::KrogerMcp.Generated.Cart.Kiota.Models.Cart.CartItemModel_modality? Modality { get; set; }
        /// <summary>The quantity of the item.</summary>
        public int? Quantity { get; set; }
        /// <summary>The `UPC` of the item.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Upc { get; set; }
#nullable restore
#else
        public string Upc { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::KrogerMcp.Generated.Cart.Kiota.Models.Cart.CartItemModel"/> and sets the default values.
        /// </summary>
        public CartItemModel()
        {
            AdditionalData = new Dictionary<string, object>();
            Modality = global::KrogerMcp.Generated.Cart.Kiota.Models.Cart.CartItemModel_modality.PICKUP;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::KrogerMcp.Generated.Cart.Kiota.Models.Cart.CartItemModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::KrogerMcp.Generated.Cart.Kiota.Models.Cart.CartItemModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::KrogerMcp.Generated.Cart.Kiota.Models.Cart.CartItemModel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "modality", n => { Modality = n.GetEnumValue<global::KrogerMcp.Generated.Cart.Kiota.Models.Cart.CartItemModel_modality>(); } },
                { "quantity", n => { Quantity = n.GetIntValue(); } },
                { "upc", n => { Upc = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::KrogerMcp.Generated.Cart.Kiota.Models.Cart.CartItemModel_modality>("modality", Modality);
            writer.WriteIntValue("quantity", Quantity);
            writer.WriteStringValue("upc", Upc);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
