// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace KrogerMcp.Generated.Products.Kiota.Models.Products
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class NutrientModel : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The code property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Code { get; set; }
#nullable restore
#else
        public string Code { get; set; }
#endif
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The displayName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayName { get; set; }
#nullable restore
#else
        public string DisplayName { get; set; }
#endif
        /// <summary>The percentDailyIntake property</summary>
        public double? PercentDailyIntake { get; set; }
        /// <summary>The precision property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::KrogerMcp.Generated.Products.Kiota.Models.Products.NutrientModel_precision? Precision { get; set; }
#nullable restore
#else
        public global::KrogerMcp.Generated.Products.Kiota.Models.Products.NutrientModel_precision Precision { get; set; }
#endif
        /// <summary>The quantity property</summary>
        public double? Quantity { get; set; }
        /// <summary>The unitOfMeasure property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::KrogerMcp.Generated.Products.Kiota.Models.Products.NutrientModel_unitOfMeasure? UnitOfMeasure { get; set; }
#nullable restore
#else
        public global::KrogerMcp.Generated.Products.Kiota.Models.Products.NutrientModel_unitOfMeasure UnitOfMeasure { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::KrogerMcp.Generated.Products.Kiota.Models.Products.NutrientModel"/> and sets the default values.
        /// </summary>
        public NutrientModel()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::KrogerMcp.Generated.Products.Kiota.Models.Products.NutrientModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::KrogerMcp.Generated.Products.Kiota.Models.Products.NutrientModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::KrogerMcp.Generated.Products.Kiota.Models.Products.NutrientModel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "code", n => { Code = n.GetStringValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "displayName", n => { DisplayName = n.GetStringValue(); } },
                { "percentDailyIntake", n => { PercentDailyIntake = n.GetDoubleValue(); } },
                { "precision", n => { Precision = n.GetObjectValue<global::KrogerMcp.Generated.Products.Kiota.Models.Products.NutrientModel_precision>(global::KrogerMcp.Generated.Products.Kiota.Models.Products.NutrientModel_precision.CreateFromDiscriminatorValue); } },
                { "quantity", n => { Quantity = n.GetDoubleValue(); } },
                { "unitOfMeasure", n => { UnitOfMeasure = n.GetObjectValue<global::KrogerMcp.Generated.Products.Kiota.Models.Products.NutrientModel_unitOfMeasure>(global::KrogerMcp.Generated.Products.Kiota.Models.Products.NutrientModel_unitOfMeasure.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("code", Code);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("displayName", DisplayName);
            writer.WriteDoubleValue("percentDailyIntake", PercentDailyIntake);
            writer.WriteObjectValue<global::KrogerMcp.Generated.Products.Kiota.Models.Products.NutrientModel_precision>("precision", Precision);
            writer.WriteDoubleValue("quantity", Quantity);
            writer.WriteObjectValue<global::KrogerMcp.Generated.Products.Kiota.Models.Products.NutrientModel_unitOfMeasure>("unitOfMeasure", UnitOfMeasure);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
