// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace KrogerMcp.Generated.Products.Kiota.Models.Products
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class NutritionInformationModel : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The dailyValueIntakeReference property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DailyValueIntakeReference { get; set; }
#nullable restore
#else
        public string DailyValueIntakeReference { get; set; }
#endif
        /// <summary>The ingredientStatement property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IngredientStatement { get; set; }
#nullable restore
#else
        public string IngredientStatement { get; set; }
#endif
        /// <summary>The nutrients property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::KrogerMcp.Generated.Products.Kiota.Models.Products.NutrientModel>? Nutrients { get; set; }
#nullable restore
#else
        public List<global::KrogerMcp.Generated.Products.Kiota.Models.Products.NutrientModel> Nutrients { get; set; }
#endif
        /// <summary>The nutritionalRating property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NutritionalRating { get; set; }
#nullable restore
#else
        public string NutritionalRating { get; set; }
#endif
        /// <summary>The preparationState property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::KrogerMcp.Generated.Products.Kiota.Models.Products.NutritionInformationModel_preparationState? PreparationState { get; set; }
#nullable restore
#else
        public global::KrogerMcp.Generated.Products.Kiota.Models.Products.NutritionInformationModel_preparationState PreparationState { get; set; }
#endif
        /// <summary>The servingSize property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::KrogerMcp.Generated.Products.Kiota.Models.Products.ServingSizeModel? ServingSize { get; set; }
#nullable restore
#else
        public global::KrogerMcp.Generated.Products.Kiota.Models.Products.ServingSizeModel ServingSize { get; set; }
#endif
        /// <summary>The servingsPerPackage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::KrogerMcp.Generated.Products.Kiota.Models.Products.NutritionInformationModel_servingsPerPackage? ServingsPerPackage { get; set; }
#nullable restore
#else
        public global::KrogerMcp.Generated.Products.Kiota.Models.Products.NutritionInformationModel_servingsPerPackage ServingsPerPackage { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::KrogerMcp.Generated.Products.Kiota.Models.Products.NutritionInformationModel"/> and sets the default values.
        /// </summary>
        public NutritionInformationModel()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::KrogerMcp.Generated.Products.Kiota.Models.Products.NutritionInformationModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::KrogerMcp.Generated.Products.Kiota.Models.Products.NutritionInformationModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::KrogerMcp.Generated.Products.Kiota.Models.Products.NutritionInformationModel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "dailyValueIntakeReference", n => { DailyValueIntakeReference = n.GetStringValue(); } },
                { "ingredientStatement", n => { IngredientStatement = n.GetStringValue(); } },
                { "nutrients", n => { Nutrients = n.GetCollectionOfObjectValues<global::KrogerMcp.Generated.Products.Kiota.Models.Products.NutrientModel>(global::KrogerMcp.Generated.Products.Kiota.Models.Products.NutrientModel.CreateFromDiscriminatorValue)?.AsList(); } },
                { "nutritionalRating", n => { NutritionalRating = n.GetStringValue(); } },
                { "preparationState", n => { PreparationState = n.GetObjectValue<global::KrogerMcp.Generated.Products.Kiota.Models.Products.NutritionInformationModel_preparationState>(global::KrogerMcp.Generated.Products.Kiota.Models.Products.NutritionInformationModel_preparationState.CreateFromDiscriminatorValue); } },
                { "servingSize", n => { ServingSize = n.GetObjectValue<global::KrogerMcp.Generated.Products.Kiota.Models.Products.ServingSizeModel>(global::KrogerMcp.Generated.Products.Kiota.Models.Products.ServingSizeModel.CreateFromDiscriminatorValue); } },
                { "servingsPerPackage", n => { ServingsPerPackage = n.GetObjectValue<global::KrogerMcp.Generated.Products.Kiota.Models.Products.NutritionInformationModel_servingsPerPackage>(global::KrogerMcp.Generated.Products.Kiota.Models.Products.NutritionInformationModel_servingsPerPackage.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("dailyValueIntakeReference", DailyValueIntakeReference);
            writer.WriteStringValue("ingredientStatement", IngredientStatement);
            writer.WriteCollectionOfObjectValues<global::KrogerMcp.Generated.Products.Kiota.Models.Products.NutrientModel>("nutrients", Nutrients);
            writer.WriteStringValue("nutritionalRating", NutritionalRating);
            writer.WriteObjectValue<global::KrogerMcp.Generated.Products.Kiota.Models.Products.NutritionInformationModel_preparationState>("preparationState", PreparationState);
            writer.WriteObjectValue<global::KrogerMcp.Generated.Products.Kiota.Models.Products.ServingSizeModel>("servingSize", ServingSize);
            writer.WriteObjectValue<global::KrogerMcp.Generated.Products.Kiota.Models.Products.NutritionInformationModel_servingsPerPackage>("servingsPerPackage", ServingsPerPackage);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
