// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace KrogerMcp.Generated.Products.Kiota.Models.Products
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ProductModel_ratingsAndReviews : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The average overall rating of the product.</summary>
        public double? AverageOverallRating { get; set; }
        /// <summary>The total number of reviews for the product.</summary>
        public int? TotalReviewCount { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductModel_ratingsAndReviews"/> and sets the default values.
        /// </summary>
        public ProductModel_ratingsAndReviews()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductModel_ratingsAndReviews"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductModel_ratingsAndReviews CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductModel_ratingsAndReviews();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "averageOverallRating", n => { AverageOverallRating = n.GetDoubleValue(); } },
                { "totalReviewCount", n => { TotalReviewCount = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("averageOverallRating", AverageOverallRating);
            writer.WriteIntValue("totalReviewCount", TotalReviewCount);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
