// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace KrogerMcp.Generated.Products.Kiota.Models.Products
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ProductAisleLocationModel : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The bay number of the aisle.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BayNumber { get; set; }
#nullable restore
#else
        public string BayNumber { get; set; }
#endif
        /// <summary>The location in the store.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The aisle number in the store.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Number { get; set; }
#nullable restore
#else
        public string Number { get; set; }
#endif
        /// <summary>The number of facings.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NumberOfFacings { get; set; }
#nullable restore
#else
        public string NumberOfFacings { get; set; }
#endif
        /// <summary>The sequence of the aisle in the store.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SequenceNumber { get; set; }
#nullable restore
#else
        public string SequenceNumber { get; set; }
#endif
        /// <summary>The shelf number in the aisle.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ShelfNumber { get; set; }
#nullable restore
#else
        public string ShelfNumber { get; set; }
#endif
        /// <summary>The position of the shelf in the bay.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ShelfPositionInBay { get; set; }
#nullable restore
#else
        public string ShelfPositionInBay { get; set; }
#endif
        /// <summary>The side of the aisle where the product is located.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Side { get; set; }
#nullable restore
#else
        public string Side { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductAisleLocationModel"/> and sets the default values.
        /// </summary>
        public ProductAisleLocationModel()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductAisleLocationModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductAisleLocationModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductAisleLocationModel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bayNumber", n => { BayNumber = n.GetStringValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "number", n => { Number = n.GetStringValue(); } },
                { "numberOfFacings", n => { NumberOfFacings = n.GetStringValue(); } },
                { "sequenceNumber", n => { SequenceNumber = n.GetStringValue(); } },
                { "shelfNumber", n => { ShelfNumber = n.GetStringValue(); } },
                { "shelfPositionInBay", n => { ShelfPositionInBay = n.GetStringValue(); } },
                { "side", n => { Side = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("bayNumber", BayNumber);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("number", Number);
            writer.WriteStringValue("numberOfFacings", NumberOfFacings);
            writer.WriteStringValue("sequenceNumber", SequenceNumber);
            writer.WriteStringValue("shelfNumber", ShelfNumber);
            writer.WriteStringValue("shelfPositionInBay", ShelfPositionInBay);
            writer.WriteStringValue("side", Side);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
