// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace KrogerMcp.Generated.Products.Kiota.Models.Products
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ProductItemPriceModel : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The effectiveDate property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::KrogerMcp.Generated.Products.Kiota.Models.Products.DateValueModel? EffectiveDate { get; set; }
#nullable restore
#else
        public global::KrogerMcp.Generated.Products.Kiota.Models.Products.DateValueModel EffectiveDate { get; set; }
#endif
        /// <summary>The expirationDate property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::KrogerMcp.Generated.Products.Kiota.Models.Products.DateValueModel? ExpirationDate { get; set; }
#nullable restore
#else
        public global::KrogerMcp.Generated.Products.Kiota.Models.Products.DateValueModel ExpirationDate { get; set; }
#endif
        /// <summary>The sale price of the item.</summary>
        public double? Promo { get; set; }
        /// <summary>The estimated sale price of 1 unit of the item.</summary>
        public double? PromoPerUnitEstimate { get; set; }
        /// <summary>The regular price of the item.</summary>
        public double? Regular { get; set; }
        /// <summary>The estimated price of 1 unit of the item.</summary>
        public double? RegularPerUnitEstimate { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductItemPriceModel"/> and sets the default values.
        /// </summary>
        public ProductItemPriceModel()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductItemPriceModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductItemPriceModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductItemPriceModel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "effectiveDate", n => { EffectiveDate = n.GetObjectValue<global::KrogerMcp.Generated.Products.Kiota.Models.Products.DateValueModel>(global::KrogerMcp.Generated.Products.Kiota.Models.Products.DateValueModel.CreateFromDiscriminatorValue); } },
                { "expirationDate", n => { ExpirationDate = n.GetObjectValue<global::KrogerMcp.Generated.Products.Kiota.Models.Products.DateValueModel>(global::KrogerMcp.Generated.Products.Kiota.Models.Products.DateValueModel.CreateFromDiscriminatorValue); } },
                { "promo", n => { Promo = n.GetDoubleValue(); } },
                { "promoPerUnitEstimate", n => { PromoPerUnitEstimate = n.GetDoubleValue(); } },
                { "regular", n => { Regular = n.GetDoubleValue(); } },
                { "regularPerUnitEstimate", n => { RegularPerUnitEstimate = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::KrogerMcp.Generated.Products.Kiota.Models.Products.DateValueModel>("effectiveDate", EffectiveDate);
            writer.WriteObjectValue<global::KrogerMcp.Generated.Products.Kiota.Models.Products.DateValueModel>("expirationDate", ExpirationDate);
            writer.WriteDoubleValue("promo", Promo);
            writer.WriteDoubleValue("promoPerUnitEstimate", PromoPerUnitEstimate);
            writer.WriteDoubleValue("regular", Regular);
            writer.WriteDoubleValue("regularPerUnitEstimate", RegularPerUnitEstimate);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
