// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace KrogerMcp.Generated.Products.Kiota.Models.Products
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ProductModel : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Indicates if the product has an age restriction.</summary>
        public bool? AgeRestriction { get; set; }
        /// <summary>The aisleLocations property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductAisleLocationModel>? AisleLocations { get; set; }
#nullable restore
#else
        public List<global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductAisleLocationModel> AisleLocations { get; set; }
#endif
        /// <summary>Indicates if the product contains alcohol.</summary>
        public bool? Alcohol { get; set; }
        /// <summary>The proof of the alcohol in the product.</summary>
        public int? AlcoholProof { get; set; }
        /// <summary>The alias ProductId of the product to return.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AliasProductIds { get; set; }
#nullable restore
#else
        public List<string> AliasProductIds { get; set; }
#endif
        /// <summary>The allergens property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::KrogerMcp.Generated.Products.Kiota.Models.Products.AllergenModel>? Allergens { get; set; }
#nullable restore
#else
        public List<global::KrogerMcp.Generated.Products.Kiota.Models.Products.AllergenModel> Allergens { get; set; }
#endif
        /// <summary>The description of the allergens for the product.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AllergensDescription { get; set; }
#nullable restore
#else
        public string AllergensDescription { get; set; }
#endif
        /// <summary>The brand name of the product.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Brand { get; set; }
#nullable restore
#else
        public string Brand { get; set; }
#endif
        /// <summary>The category the product belongs to.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Categories { get; set; }
#nullable restore
#else
        public List<string> Categories { get; set; }
#endif
        /// <summary>Indicates if the product is certified for Passover.</summary>
        public bool? CertifiedForPassover { get; set; }
        /// <summary>The country of origin of the product.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CountryOrigin { get; set; }
#nullable restore
#else
        public string CountryOrigin { get; set; }
#endif
        /// <summary>The name of the product.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Indicates if the product is hypoallergenic.</summary>
        public bool? Hypoallergenic { get; set; }
        /// <summary>The images property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductImageModel>? Images { get; set; }
#nullable restore
#else
        public List<global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductImageModel> Images { get; set; }
#endif
        /// <summary>Information about the product&apos;s size.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductBoxedDimensionsModel? ItemInformation { get; set; }
#nullable restore
#else
        public global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductBoxedDimensionsModel ItemInformation { get; set; }
#endif
        /// <summary>The items property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductItemModel>? Items { get; set; }
#nullable restore
#else
        public List<global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductItemModel> Items { get; set; }
#endif
        /// <summary>Any manufacturer declarations for the product.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ManufacturerDeclarations { get; set; }
#nullable restore
#else
        public List<string> ManufacturerDeclarations { get; set; }
#endif
        /// <summary>Indicates if the product is non-GMO.</summary>
        public bool? NonGmo { get; set; }
        /// <summary>The name of the non-GMO claim.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NonGmoClaimName { get; set; }
#nullable restore
#else
        public string NonGmoClaimName { get; set; }
#endif
        /// <summary>The nutritionInformation property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::KrogerMcp.Generated.Products.Kiota.Models.Products.NutritionInformationModel? NutritionInformation { get; set; }
#nullable restore
#else
        public global::KrogerMcp.Generated.Products.Kiota.Models.Products.NutritionInformationModel NutritionInformation { get; set; }
#endif
        /// <summary>The name of the organic claim.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrganicClaimName { get; set; }
#nullable restore
#else
        public string OrganicClaimName { get; set; }
#endif
        /// <summary>The UPC of the product.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProductId { get; set; }
#nullable restore
#else
        public string ProductId { get; set; }
#endif
        /// <summary>The URI of the product page.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProductPageURI { get; set; }
#nullable restore
#else
        public string ProductPageURI { get; set; }
#endif
        /// <summary>The ratingsAndReviews property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductModel_ratingsAndReviews? RatingsAndReviews { get; set; }
#nullable restore
#else
        public global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductModel_ratingsAndReviews RatingsAndReviews { get; set; }
#endif
        /// <summary>The description of the product to appear on the receipt.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReceiptDescription { get; set; }
#nullable restore
#else
        public string ReceiptDescription { get; set; }
#endif
        /// <summary>The retstrictions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::KrogerMcp.Generated.Products.Kiota.Models.Products.RestrictionsModel? Retstrictions { get; set; }
#nullable restore
#else
        public global::KrogerMcp.Generated.Products.Kiota.Models.Products.RestrictionsModel Retstrictions { get; set; }
#endif
        /// <summary>Indicates if the product is eligible for SNAP benefits.</summary>
        public bool? SnapEligible { get; set; }
        /// <summary>The sweeteningMethods property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductModel_sweeteningMethods? SweeteningMethods { get; set; }
#nullable restore
#else
        public global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductModel_sweeteningMethods SweeteningMethods { get; set; }
#endif
        /// <summary>Information about the item&apos;s temperature requirements.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductTemperatureModel? Temperature { get; set; }
#nullable restore
#else
        public global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductTemperatureModel Temperature { get; set; }
#endif
        /// <summary>The UPC of the product.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Upc { get; set; }
#nullable restore
#else
        public string Upc { get; set; }
#endif
        /// <summary>Any warnings for the product.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Warnings { get; set; }
#nullable restore
#else
        public string Warnings { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductModel"/> and sets the default values.
        /// </summary>
        public ProductModel()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductModel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "ageRestriction", n => { AgeRestriction = n.GetBoolValue(); } },
                { "aisleLocations", n => { AisleLocations = n.GetCollectionOfObjectValues<global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductAisleLocationModel>(global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductAisleLocationModel.CreateFromDiscriminatorValue)?.AsList(); } },
                { "alcohol", n => { Alcohol = n.GetBoolValue(); } },
                { "alcoholProof", n => { AlcoholProof = n.GetIntValue(); } },
                { "aliasProductIds", n => { AliasProductIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "allergens", n => { Allergens = n.GetCollectionOfObjectValues<global::KrogerMcp.Generated.Products.Kiota.Models.Products.AllergenModel>(global::KrogerMcp.Generated.Products.Kiota.Models.Products.AllergenModel.CreateFromDiscriminatorValue)?.AsList(); } },
                { "allergensDescription", n => { AllergensDescription = n.GetStringValue(); } },
                { "brand", n => { Brand = n.GetStringValue(); } },
                { "categories", n => { Categories = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "certifiedForPassover", n => { CertifiedForPassover = n.GetBoolValue(); } },
                { "countryOrigin", n => { CountryOrigin = n.GetStringValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "hypoallergenic", n => { Hypoallergenic = n.GetBoolValue(); } },
                { "images", n => { Images = n.GetCollectionOfObjectValues<global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductImageModel>(global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductImageModel.CreateFromDiscriminatorValue)?.AsList(); } },
                { "itemInformation", n => { ItemInformation = n.GetObjectValue<global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductBoxedDimensionsModel>(global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductBoxedDimensionsModel.CreateFromDiscriminatorValue); } },
                { "items", n => { Items = n.GetCollectionOfObjectValues<global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductItemModel>(global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductItemModel.CreateFromDiscriminatorValue)?.AsList(); } },
                { "manufacturerDeclarations", n => { ManufacturerDeclarations = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "nonGmo", n => { NonGmo = n.GetBoolValue(); } },
                { "nonGmoClaimName", n => { NonGmoClaimName = n.GetStringValue(); } },
                { "nutritionInformation", n => { NutritionInformation = n.GetObjectValue<global::KrogerMcp.Generated.Products.Kiota.Models.Products.NutritionInformationModel>(global::KrogerMcp.Generated.Products.Kiota.Models.Products.NutritionInformationModel.CreateFromDiscriminatorValue); } },
                { "organicClaimName", n => { OrganicClaimName = n.GetStringValue(); } },
                { "productId", n => { ProductId = n.GetStringValue(); } },
                { "productPageURI", n => { ProductPageURI = n.GetStringValue(); } },
                { "ratingsAndReviews", n => { RatingsAndReviews = n.GetObjectValue<global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductModel_ratingsAndReviews>(global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductModel_ratingsAndReviews.CreateFromDiscriminatorValue); } },
                { "receiptDescription", n => { ReceiptDescription = n.GetStringValue(); } },
                { "retstrictions", n => { Retstrictions = n.GetObjectValue<global::KrogerMcp.Generated.Products.Kiota.Models.Products.RestrictionsModel>(global::KrogerMcp.Generated.Products.Kiota.Models.Products.RestrictionsModel.CreateFromDiscriminatorValue); } },
                { "snapEligible", n => { SnapEligible = n.GetBoolValue(); } },
                { "sweeteningMethods", n => { SweeteningMethods = n.GetObjectValue<global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductModel_sweeteningMethods>(global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductModel_sweeteningMethods.CreateFromDiscriminatorValue); } },
                { "temperature", n => { Temperature = n.GetObjectValue<global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductTemperatureModel>(global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductTemperatureModel.CreateFromDiscriminatorValue); } },
                { "upc", n => { Upc = n.GetStringValue(); } },
                { "warnings", n => { Warnings = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("ageRestriction", AgeRestriction);
            writer.WriteCollectionOfObjectValues<global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductAisleLocationModel>("aisleLocations", AisleLocations);
            writer.WriteBoolValue("alcohol", Alcohol);
            writer.WriteIntValue("alcoholProof", AlcoholProof);
            writer.WriteCollectionOfPrimitiveValues<string>("aliasProductIds", AliasProductIds);
            writer.WriteCollectionOfObjectValues<global::KrogerMcp.Generated.Products.Kiota.Models.Products.AllergenModel>("allergens", Allergens);
            writer.WriteStringValue("allergensDescription", AllergensDescription);
            writer.WriteStringValue("brand", Brand);
            writer.WriteCollectionOfPrimitiveValues<string>("categories", Categories);
            writer.WriteBoolValue("certifiedForPassover", CertifiedForPassover);
            writer.WriteStringValue("countryOrigin", CountryOrigin);
            writer.WriteStringValue("description", Description);
            writer.WriteBoolValue("hypoallergenic", Hypoallergenic);
            writer.WriteCollectionOfObjectValues<global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductImageModel>("images", Images);
            writer.WriteObjectValue<global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductBoxedDimensionsModel>("itemInformation", ItemInformation);
            writer.WriteCollectionOfObjectValues<global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductItemModel>("items", Items);
            writer.WriteCollectionOfPrimitiveValues<string>("manufacturerDeclarations", ManufacturerDeclarations);
            writer.WriteBoolValue("nonGmo", NonGmo);
            writer.WriteStringValue("nonGmoClaimName", NonGmoClaimName);
            writer.WriteObjectValue<global::KrogerMcp.Generated.Products.Kiota.Models.Products.NutritionInformationModel>("nutritionInformation", NutritionInformation);
            writer.WriteStringValue("organicClaimName", OrganicClaimName);
            writer.WriteStringValue("productId", ProductId);
            writer.WriteStringValue("productPageURI", ProductPageURI);
            writer.WriteObjectValue<global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductModel_ratingsAndReviews>("ratingsAndReviews", RatingsAndReviews);
            writer.WriteStringValue("receiptDescription", ReceiptDescription);
            writer.WriteObjectValue<global::KrogerMcp.Generated.Products.Kiota.Models.Products.RestrictionsModel>("retstrictions", Retstrictions);
            writer.WriteBoolValue("snapEligible", SnapEligible);
            writer.WriteObjectValue<global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductModel_sweeteningMethods>("sweeteningMethods", SweeteningMethods);
            writer.WriteObjectValue<global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductTemperatureModel>("temperature", Temperature);
            writer.WriteStringValue("upc", Upc);
            writer.WriteStringValue("warnings", Warnings);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
