// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace KrogerMcp.Generated.Products.Kiota.Models.Products
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ProductItemModel : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The favorite property</summary>
        public bool? Favorite { get; set; }
        /// <summary>The fulfillment property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductItemFulfillmentModel? Fulfillment { get; set; }
#nullable restore
#else
        public global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductItemFulfillmentModel Fulfillment { get; set; }
#endif
        /// <summary>The inventory property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductItemInventoryModel? Inventory { get; set; }
#nullable restore
#else
        public global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductItemInventoryModel Inventory { get; set; }
#endif
        /// <summary>The UPC of the item.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ItemId { get; set; }
#nullable restore
#else
        public string ItemId { get; set; }
#endif
        /// <summary>The nationalPrice property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductItemPriceModel? NationalPrice { get; set; }
#nullable restore
#else
        public global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductItemPriceModel NationalPrice { get; set; }
#endif
        /// <summary>The price property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductItemPriceModel? Price { get; set; }
#nullable restore
#else
        public global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductItemPriceModel Price { get; set; }
#endif
        /// <summary>A description of the item size.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Size { get; set; }
#nullable restore
#else
        public string Size { get; set; }
#endif
        /// <summary>Indicates how this item is sold. Values returned are typically either &quot;weight&quot; or &quot;unit&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SoldBy { get; set; }
#nullable restore
#else
        public string SoldBy { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductItemModel"/> and sets the default values.
        /// </summary>
        public ProductItemModel()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductItemModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductItemModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductItemModel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "favorite", n => { Favorite = n.GetBoolValue(); } },
                { "fulfillment", n => { Fulfillment = n.GetObjectValue<global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductItemFulfillmentModel>(global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductItemFulfillmentModel.CreateFromDiscriminatorValue); } },
                { "inventory", n => { Inventory = n.GetObjectValue<global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductItemInventoryModel>(global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductItemInventoryModel.CreateFromDiscriminatorValue); } },
                { "itemId", n => { ItemId = n.GetStringValue(); } },
                { "nationalPrice", n => { NationalPrice = n.GetObjectValue<global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductItemPriceModel>(global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductItemPriceModel.CreateFromDiscriminatorValue); } },
                { "price", n => { Price = n.GetObjectValue<global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductItemPriceModel>(global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductItemPriceModel.CreateFromDiscriminatorValue); } },
                { "size", n => { Size = n.GetStringValue(); } },
                { "soldBy", n => { SoldBy = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("favorite", Favorite);
            writer.WriteObjectValue<global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductItemFulfillmentModel>("fulfillment", Fulfillment);
            writer.WriteObjectValue<global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductItemInventoryModel>("inventory", Inventory);
            writer.WriteStringValue("itemId", ItemId);
            writer.WriteObjectValue<global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductItemPriceModel>("nationalPrice", NationalPrice);
            writer.WriteObjectValue<global::KrogerMcp.Generated.Products.Kiota.Models.Products.ProductItemPriceModel>("price", Price);
            writer.WriteStringValue("size", Size);
            writer.WriteStringValue("soldBy", SoldBy);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
