// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace KrogerMcp.Generated.Products.Kiota.Models.Products
{
    /// <summary>Indicates the level of stock.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ProductItemInventoryModel_stockLevel
    {
        [EnumMember(Value = "HIGH")]
        #pragma warning disable CS1591
        HIGH,
        #pragma warning restore CS1591
        [EnumMember(Value = "LOW")]
        #pragma warning disable CS1591
        LOW,
        #pragma warning restore CS1591
        [EnumMember(Value = "TEMPORARILY_OUT_OF_STOCK")]
        #pragma warning disable CS1591
        TEMPORARILY_OUT_OF_STOCK,
        #pragma warning restore CS1591
    }
}
