// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace KrogerMcp.Generated.Locations.Kiota.Models.Locations
{
    /// <summary>
    /// The e-commerce modality capabilities for this chain.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Chain_modalityCapabilities : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Flag for if this chain supports e-commerce pickup.</summary>
        public bool? Curbside { get; set; }
        /// <summary>Flag for if this chain supports e-commerce delivery.</summary>
        public bool? Delivery { get; set; }
        /// <summary>Flag for if this chain supports e-commerce in-store shopping.</summary>
        public bool? Instore { get; set; }
        /// <summary>Flag for if this chain supports e-commerce shipping.</summary>
        public bool? Shiptohome { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.Chain_modalityCapabilities"/> and sets the default values.
        /// </summary>
        public Chain_modalityCapabilities()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.Chain_modalityCapabilities"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.Chain_modalityCapabilities CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.Chain_modalityCapabilities();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "curbside", n => { Curbside = n.GetBoolValue(); } },
                { "delivery", n => { Delivery = n.GetBoolValue(); } },
                { "instore", n => { Instore = n.GetBoolValue(); } },
                { "shiptohome", n => { Shiptohome = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("curbside", Curbside);
            writer.WriteBoolValue("delivery", Delivery);
            writer.WriteBoolValue("instore", Instore);
            writer.WriteBoolValue("shiptohome", Shiptohome);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
