// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace KrogerMcp.Generated.Locations.Kiota.Models.Locations
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Chain : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The Apple app ID for this chain.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AppleAppId { get; set; }
#nullable restore
#else
        public string AppleAppId { get; set; }
#endif
        /// <summary>The default title for this chain.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DefaultTitle { get; set; }
#nullable restore
#else
        public string DefaultTitle { get; set; }
#endif
        /// <summary>The description for this chain.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>A list of all management division numbers within the brand.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? DivisionNumbers { get; set; }
#nullable restore
#else
        public List<string> DivisionNumbers { get; set; }
#endif
        /// <summary>The domain of the chain.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Domain { get; set; }
#nullable restore
#else
        public string Domain { get; set; }
#endif
        /// <summary>The friendly name for this chain.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FriendlyBannerName { get; set; }
#nullable restore
#else
        public string FriendlyBannerName { get; set; }
#endif
        /// <summary>The Google app ID for this chain.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GoogleAppId { get; set; }
#nullable restore
#else
        public string GoogleAppId { get; set; }
#endif
        /// <summary>The e-commerce modality capabilities for this chain.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.Chain_modalityCapabilities? ModalityCapabilities { get; set; }
#nullable restore
#else
        public global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.Chain_modalityCapabilities ModalityCapabilities { get; set; }
#endif
        /// <summary>The name of the chain.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The theme color for this chain.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ThemeColor { get; set; }
#nullable restore
#else
        public string ThemeColor { get; set; }
#endif
        /// <summary>The title extension for this chain.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TitleExtension { get; set; }
#nullable restore
#else
        public string TitleExtension { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.Chain"/> and sets the default values.
        /// </summary>
        public Chain()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.Chain"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.Chain CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.Chain();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "appleAppId", n => { AppleAppId = n.GetStringValue(); } },
                { "defaultTitle", n => { DefaultTitle = n.GetStringValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "divisionNumbers", n => { DivisionNumbers = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "domain", n => { Domain = n.GetStringValue(); } },
                { "friendlyBannerName", n => { FriendlyBannerName = n.GetStringValue(); } },
                { "googleAppId", n => { GoogleAppId = n.GetStringValue(); } },
                { "modalityCapabilities", n => { ModalityCapabilities = n.GetObjectValue<global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.Chain_modalityCapabilities>(global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.Chain_modalityCapabilities.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "themeColor", n => { ThemeColor = n.GetStringValue(); } },
                { "titleExtension", n => { TitleExtension = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("appleAppId", AppleAppId);
            writer.WriteStringValue("defaultTitle", DefaultTitle);
            writer.WriteStringValue("description", Description);
            writer.WriteCollectionOfPrimitiveValues<string>("divisionNumbers", DivisionNumbers);
            writer.WriteStringValue("domain", Domain);
            writer.WriteStringValue("friendlyBannerName", FriendlyBannerName);
            writer.WriteStringValue("googleAppId", GoogleAppId);
            writer.WriteObjectValue<global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.Chain_modalityCapabilities>("modalityCapabilities", ModalityCapabilities);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("themeColor", ThemeColor);
            writer.WriteStringValue("titleExtension", TitleExtension);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
