// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace KrogerMcp.Generated.Locations.Kiota.Models.Locations
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Location : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The address property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.Address? Address { get; set; }
#nullable restore
#else
        public global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.Address Address { get; set; }
#endif
        /// <summary>The name of the chain.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Chain { get; set; }
#nullable restore
#else
        public string Chain { get; set; }
#endif
        /// <summary>The available departments at the location.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.DepartmentAtLocation>? Departments { get; set; }
#nullable restore
#else
        public List<global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.DepartmentAtLocation> Departments { get; set; }
#endif
        /// <summary>The 3-digit management division number.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DivisionNumber { get; set; }
#nullable restore
#else
        public string DivisionNumber { get; set; }
#endif
        /// <summary>The geolocation property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.GeoLocation? Geolocation { get; set; }
#nullable restore
#else
        public global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.GeoLocation Geolocation { get; set; }
#endif
        /// <summary>The hours property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.LocationHours? Hours { get; set; }
#nullable restore
#else
        public global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.LocationHours Hours { get; set; }
#endif
        /// <summary>The 3-digit management division number followed by the 5-digit store number.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LocationId { get; set; }
#nullable restore
#else
        public string LocationId { get; set; }
#endif
        /// <summary>The name of the location. The name generally consists of the chain followed by a vanity name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The phone number of the location.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Phone { get; set; }
#nullable restore
#else
        public string Phone { get; set; }
#endif
        /// <summary>The 5-digit store number.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StoreNumber { get; set; }
#nullable restore
#else
        public string StoreNumber { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.Location"/> and sets the default values.
        /// </summary>
        public Location()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.Location"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.Location CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.Location();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "address", n => { Address = n.GetObjectValue<global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.Address>(global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.Address.CreateFromDiscriminatorValue); } },
                { "chain", n => { Chain = n.GetStringValue(); } },
                { "departments", n => { Departments = n.GetCollectionOfObjectValues<global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.DepartmentAtLocation>(global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.DepartmentAtLocation.CreateFromDiscriminatorValue)?.AsList(); } },
                { "divisionNumber", n => { DivisionNumber = n.GetStringValue(); } },
                { "geolocation", n => { Geolocation = n.GetObjectValue<global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.GeoLocation>(global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.GeoLocation.CreateFromDiscriminatorValue); } },
                { "hours", n => { Hours = n.GetObjectValue<global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.LocationHours>(global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.LocationHours.CreateFromDiscriminatorValue); } },
                { "locationId", n => { LocationId = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "phone", n => { Phone = n.GetStringValue(); } },
                { "storeNumber", n => { StoreNumber = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.Address>("address", Address);
            writer.WriteStringValue("chain", Chain);
            writer.WriteCollectionOfObjectValues<global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.DepartmentAtLocation>("departments", Departments);
            writer.WriteStringValue("divisionNumber", DivisionNumber);
            writer.WriteObjectValue<global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.GeoLocation>("geolocation", Geolocation);
            writer.WriteObjectValue<global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.LocationHours>("hours", Hours);
            writer.WriteStringValue("locationId", LocationId);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("phone", Phone);
            writer.WriteStringValue("storeNumber", StoreNumber);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
