// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace KrogerMcp.Generated.Locations.Kiota.Models.Locations
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class LocationHours : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The friday property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.DailyHours? Friday { get; set; }
#nullable restore
#else
        public global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.DailyHours Friday { get; set; }
#endif
        /// <summary>The utc timezone offset from gmt.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GmtOffset { get; set; }
#nullable restore
#else
        public string GmtOffset { get; set; }
#endif
        /// <summary>The monday property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.DailyHours? Monday { get; set; }
#nullable restore
#else
        public global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.DailyHours Monday { get; set; }
#endif
        /// <summary>Indicates if the location is open 24 hours.</summary>
        public bool? Open24 { get; set; }
        /// <summary>The saturday property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.DailyHours? Saturday { get; set; }
#nullable restore
#else
        public global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.DailyHours Saturday { get; set; }
#endif
        /// <summary>The sunday property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.DailyHours? Sunday { get; set; }
#nullable restore
#else
        public global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.DailyHours Sunday { get; set; }
#endif
        /// <summary>The thursday property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.DailyHours? Thursday { get; set; }
#nullable restore
#else
        public global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.DailyHours Thursday { get; set; }
#endif
        /// <summary>The timezone of the location.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Timezone { get; set; }
#nullable restore
#else
        public string Timezone { get; set; }
#endif
        /// <summary>The tuesday property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.DailyHours? Tuesday { get; set; }
#nullable restore
#else
        public global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.DailyHours Tuesday { get; set; }
#endif
        /// <summary>The wednesday property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.DailyHours? Wednesday { get; set; }
#nullable restore
#else
        public global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.DailyHours Wednesday { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.LocationHours"/> and sets the default values.
        /// </summary>
        public LocationHours()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.LocationHours"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.LocationHours CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.LocationHours();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "friday", n => { Friday = n.GetObjectValue<global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.DailyHours>(global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.DailyHours.CreateFromDiscriminatorValue); } },
                { "gmtOffset", n => { GmtOffset = n.GetStringValue(); } },
                { "monday", n => { Monday = n.GetObjectValue<global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.DailyHours>(global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.DailyHours.CreateFromDiscriminatorValue); } },
                { "Open24", n => { Open24 = n.GetBoolValue(); } },
                { "saturday", n => { Saturday = n.GetObjectValue<global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.DailyHours>(global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.DailyHours.CreateFromDiscriminatorValue); } },
                { "sunday", n => { Sunday = n.GetObjectValue<global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.DailyHours>(global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.DailyHours.CreateFromDiscriminatorValue); } },
                { "thursday", n => { Thursday = n.GetObjectValue<global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.DailyHours>(global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.DailyHours.CreateFromDiscriminatorValue); } },
                { "timezone", n => { Timezone = n.GetStringValue(); } },
                { "tuesday", n => { Tuesday = n.GetObjectValue<global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.DailyHours>(global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.DailyHours.CreateFromDiscriminatorValue); } },
                { "wednesday", n => { Wednesday = n.GetObjectValue<global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.DailyHours>(global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.DailyHours.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.DailyHours>("friday", Friday);
            writer.WriteStringValue("gmtOffset", GmtOffset);
            writer.WriteObjectValue<global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.DailyHours>("monday", Monday);
            writer.WriteBoolValue("Open24", Open24);
            writer.WriteObjectValue<global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.DailyHours>("saturday", Saturday);
            writer.WriteObjectValue<global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.DailyHours>("sunday", Sunday);
            writer.WriteObjectValue<global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.DailyHours>("thursday", Thursday);
            writer.WriteStringValue("timezone", Timezone);
            writer.WriteObjectValue<global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.DailyHours>("tuesday", Tuesday);
            writer.WriteObjectValue<global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.DailyHours>("wednesday", Wednesday);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
