// <auto-generated/>
#pragma warning disable CS0618
using KrogerMcp.Generated.Locations.Kiota.Models.APIError.Locations;
using KrogerMcp.Generated.Locations.Kiota.Models.APIError;
using KrogerMcp.Generated.Locations.Kiota.Models.Locations;
using KrogerMcp.Generated.Locations.Kiota.V1.Locations.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace KrogerMcp.Generated.Locations.Kiota.V1.Locations
{
    /// <summary>
    /// Builds and executes requests for operations under \v1\locations
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LocationsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the KrogerMcp.Generated.Locations.Kiota.v1.locations.item collection</summary>
        /// <param name="position">The locationId of the store.</param>
        /// <returns>A <see cref="global::KrogerMcp.Generated.Locations.Kiota.V1.Locations.Item.WithLocationItemRequestBuilder"/></returns>
        public global::KrogerMcp.Generated.Locations.Kiota.V1.Locations.Item.WithLocationItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("locationId", position);
                return new global::KrogerMcp.Generated.Locations.Kiota.V1.Locations.Item.WithLocationItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::KrogerMcp.Generated.Locations.Kiota.V1.Locations.LocationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LocationsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/locations{?filter%2Echain*,filter%2Edepartment*,filter%2Elat%2Enear*,filter%2ElatLong%2Enear*,filter%2Elimit*,filter%2ElocationId*,filter%2Elon%2Enear*,filter%2EradiusInMiles*,filter%2EzipCode%2Enear*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::KrogerMcp.Generated.Locations.Kiota.V1.Locations.LocationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LocationsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/v1/locations{?filter%2Echain*,filter%2Edepartment*,filter%2Elat%2Enear*,filter%2ElatLong%2Enear*,filter%2Elimit*,filter%2ElocationId*,filter%2Elon%2Enear*,filter%2EradiusInMiles*,filter%2EzipCode%2Enear*}", rawUrl)
        {
        }
        /// <summary>
        /// Provides access to a list of locations. If the parameter `filter.chain` is not provided, the results include all locations and chains owned by The Kroger Co.&lt;br&gt;You may include one of the following parameters to narrow search results within a geographic area:&lt;br&gt;&lt;br&gt; &lt;ul&gt; &lt;li&gt; &lt;code&gt;filter.zipCode.near&lt;/code&gt;&lt;/li&gt; &lt;li&gt; &lt;code&gt;filter.latLong.near&lt;/code&gt;&lt;/li&gt; &lt;li&gt; &lt;code&gt;filter.lat.near&lt;/code&gt; and &lt;code&gt;filter.lon.near&lt;/code&gt;&lt;/li&gt; &lt;/ul&gt;
        /// </summary>
        /// <returns>A <see cref="global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.LocationSearchResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::KrogerMcp.Generated.Locations.Kiota.Models.APIError.Unauthorized">When receiving a 401 status code</exception>
        /// <exception cref="global::KrogerMcp.Generated.Locations.Kiota.Models.APIError.NotFound">When receiving a 404 status code</exception>
        /// <exception cref="global::KrogerMcp.Generated.Locations.Kiota.Models.APIError.Locations.ServerError">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.LocationSearchResponse?> GetAsync(Action<RequestConfiguration<global::KrogerMcp.Generated.Locations.Kiota.V1.Locations.LocationsRequestBuilder.LocationsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.LocationSearchResponse> GetAsync(Action<RequestConfiguration<global::KrogerMcp.Generated.Locations.Kiota.V1.Locations.LocationsRequestBuilder.LocationsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::KrogerMcp.Generated.Locations.Kiota.Models.APIError.Unauthorized.CreateFromDiscriminatorValue },
                { "404", global::KrogerMcp.Generated.Locations.Kiota.Models.APIError.NotFound.CreateFromDiscriminatorValue },
                { "500", global::KrogerMcp.Generated.Locations.Kiota.Models.APIError.Locations.ServerError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.LocationSearchResponse>(requestInfo, global::KrogerMcp.Generated.Locations.Kiota.Models.Locations.LocationSearchResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Provides access to a list of locations. If the parameter `filter.chain` is not provided, the results include all locations and chains owned by The Kroger Co.&lt;br&gt;You may include one of the following parameters to narrow search results within a geographic area:&lt;br&gt;&lt;br&gt; &lt;ul&gt; &lt;li&gt; &lt;code&gt;filter.zipCode.near&lt;/code&gt;&lt;/li&gt; &lt;li&gt; &lt;code&gt;filter.latLong.near&lt;/code&gt;&lt;/li&gt; &lt;li&gt; &lt;code&gt;filter.lat.near&lt;/code&gt; and &lt;code&gt;filter.lon.near&lt;/code&gt;&lt;/li&gt; &lt;/ul&gt;
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::KrogerMcp.Generated.Locations.Kiota.V1.Locations.LocationsRequestBuilder.LocationsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::KrogerMcp.Generated.Locations.Kiota.V1.Locations.LocationsRequestBuilder.LocationsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::KrogerMcp.Generated.Locations.Kiota.V1.Locations.LocationsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::KrogerMcp.Generated.Locations.Kiota.V1.Locations.LocationsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::KrogerMcp.Generated.Locations.Kiota.V1.Locations.LocationsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Provides access to a list of locations. If the parameter `filter.chain` is not provided, the results include all locations and chains owned by The Kroger Co.&lt;br&gt;You may include one of the following parameters to narrow search results within a geographic area:&lt;br&gt;&lt;br&gt; &lt;ul&gt; &lt;li&gt; &lt;code&gt;filter.zipCode.near&lt;/code&gt;&lt;/li&gt; &lt;li&gt; &lt;code&gt;filter.latLong.near&lt;/code&gt;&lt;/li&gt; &lt;li&gt; &lt;code&gt;filter.lat.near&lt;/code&gt; and &lt;code&gt;filter.lon.near&lt;/code&gt;&lt;/li&gt; &lt;/ul&gt;
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class LocationsRequestBuilderGetQueryParameters 
        {
            /// <summary>The chain name of the chain. When using this filter, only stores matching the provided chain name are returned.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter%2Echain")]
            public string? FilterChain { get; set; }
#nullable restore
#else
            [QueryParameter("filter%2Echain")]
            public string FilterChain { get; set; }
#endif
            /// <summary>The departmentId of the department. Lists must be comma-separated. When using this filter, only stores that have all of the departments provided are returned.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter%2Edepartment")]
            public string? FilterDepartment { get; set; }
#nullable restore
#else
            [QueryParameter("filter%2Edepartment")]
            public string FilterDepartment { get; set; }
#endif
            /// <summary>The latitude and longitude to use as a starting point for results.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter%2ElatLong%2Enear")]
            public string? FilterLatLongNear { get; set; }
#nullable restore
#else
            [QueryParameter("filter%2ElatLong%2Enear")]
            public string FilterLatLongNear { get; set; }
#endif
            /// <summary>The latitude to use as a starting point for results.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter%2Elat%2Enear")]
            public string? FilterLatNear { get; set; }
#nullable restore
#else
            [QueryParameter("filter%2Elat%2Enear")]
            public string FilterLatNear { get; set; }
#endif
            /// <summary>The number of results to return.</summary>
            [QueryParameter("filter%2Elimit")]
            public int? FilterLimit { get; set; }
            /// <summary>Comma-separated list of locationIds.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter%2ElocationId")]
            public string? FilterLocationId { get; set; }
#nullable restore
#else
            [QueryParameter("filter%2ElocationId")]
            public string FilterLocationId { get; set; }
#endif
            /// <summary>The longitude to use as a starting point for results.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter%2Elon%2Enear")]
            public string? FilterLonNear { get; set; }
#nullable restore
#else
            [QueryParameter("filter%2Elon%2Enear")]
            public string FilterLonNear { get; set; }
#endif
            /// <summary>The mile radius of results. This will be ignored if you do not use one of the 3 starting point filters (zipCode, latLong, or lat and lon)</summary>
            [QueryParameter("filter%2EradiusInMiles")]
            public int? FilterRadiusInMiles { get; set; }
            /// <summary>The zip code to use as a starting point for results.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("filter%2EzipCode%2Enear")]
            public string? FilterZipCodeNear { get; set; }
#nullable restore
#else
            [QueryParameter("filter%2EzipCode%2Enear")]
            public string FilterZipCodeNear { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class LocationsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::KrogerMcp.Generated.Locations.Kiota.V1.Locations.LocationsRequestBuilder.LocationsRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
